# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT
# Mod Properties
mod_version=7.6
maven_group=com.connectivity
archives_base_name=connectivity
# Dependencies
fabric_version=0.144.3+26.1