name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug you're experiencing
      description: Also tell us, what did you expect to happen?
      placeholder: I did X and Y happened!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproducability
      description: Which steps are needed to reproduce this bug?
      placeholder: First do X then Y and then Z happens
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Mod up to date
      description:
      options:
        - label: Before submitting this issue I updated to the newest version and reproduced it
          required: true
  - type: input
    id: mversion
    attributes:
      label: Minecraft version
      description: What version of Minecraft are you using?
    validations:
      required: true
  - type: dropdown
    id: lversion
    attributes:
      label: Modloader version
      description: Which modloader are you using? Only Forge/Fabric is supported.
      options:
        - Forge
        - Fabric
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: Please upload your log file from logs/latest.log to https://gist.github.com/ and put in the link below. It always contains needed, important information.
      placeholder: ex. https://gist.github.com/someaddons/aa5986b9495863c3b5
    validations:
      required: true
